import streamlit as st
import colorsys
from PIL import Image, ImageDraw

# --- 1. Page Config ---
st.set_page_config(page_title="AI Interior Lab", layout="wide")

# --- 2. Logic Functions ---
def get_complementary(hex_color):
    hex_color = hex_color.lstrip('#')
    rgb = tuple(int(hex_color[i:i+2], 16) for i in (0, 2, 4))
    h, s, v = colorsys.rgb_to_hsv(rgb[0]/255, rgb[1]/255, rgb[2]/255)
    return '#%02x%02x%02x' % tuple(int(x*255) for x in colorsys.hsv_to_rgb((h + 0.5) % 1.0, s, v))

def create_ai_image(primary_hex, contrast_hex, room_text):
    """Generates a real image file using code (No Internet Needed)"""
    img = Image.new('RGB', (800, 400), color='#ffffff')
    draw = ImageDraw.Draw(img)
    
    # Draw Background Design
    draw.rectangle([0, 0, 800, 400], fill=primary_hex)
    draw.rectangle([50, 50, 750, 350], fill='#ffffff')
    
    # Draw Abstract Furniture Blocks
    draw.rectangle([100, 100, 300, 250], fill=primary_hex + "88", outline="#333")
    draw.ellipse([400, 150, 550, 300], fill=contrast_hex)
    
    return img

# --- 3. Sidebar ---
with st.sidebar:
    st.header("🛠️ Design Inputs")
    room = st.selectbox("Room Type", ["Living Room", "Bedroom", "Office"])
    style = st.selectbox("Aesthetic", ["Modern", "Industrial", "Minimalist"])
    l = st.number_input("Length (ft)", value=15)
    w = st.number_input("Width (ft)", value=12)
    user_color = st.color_picker("Theme Color", "#3498db")
    
    generate_btn = st.button("✨ Generate AI Design", use_container_width=True)

# --- 4. Main Screen ---
st.title("🏠 AI Interior Design Studio")

if generate_btn:
    comp_color = get_complementary(user_color)
    
    col1, col2 = st.columns(2)
    with col1:
        st.subheader("📐 Spatial Analysis")
        st.write(f"**Plan:** {style} {room}")
        st.write(f"**Area:** {l * w} sq. ft.")
    
    with col2:
        st.subheader("🎨 Color Palette")
        st.write(f"Primary: **{user_color}**")
        st.write(f"AI Contrast: **{comp_color}**")

    st.divider()

    # --- THE ULTIMATE FIX: GENERATED BY PILLOW ---
    st.subheader(f"AI Concept Visualization: {style} {room}")
    
    # This creates the image on the fly
    generated_img = create_ai_image(user_color, comp_color, room)
    
    # Display the locally generated image
    st.image(generated_img, caption="AI Synthetic Layout Concept", use_container_width=True)
    
    st.success("✅ Image generated locally (No external dependencies)")

else:
    st.info("👈 Enter details in the sidebar and click Generate.")
