import streamlit as st
import requests
import io
from PIL import Image

# --- 1. Setup ---
st.set_page_config(page_title="Hugging Face Interior AI", layout="wide")

# Pull Token from Secrets
try:
    API_TOKEN = st.secrets["HF_TOKEN"]
except:
    st.error("Missing HF_TOKEN in Streamlit Secrets!")
    st.stop()

# We use the Stable Diffusion model for high-quality interiors
API_URL = "https://api-inference.huggingface.co/models/runwayml/stable-diffusion-v1-5"
headers = {"Authorization": f"Bearer {API_TOKEN}"}

def query_model(payload):
    response = requests.post(API_URL, headers=headers, json=payload)
    return response.content

# --- 2. Sidebar ---
with st.sidebar:
    st.header("🤖 AI Model Settings")
    room = st.selectbox("Room Type", ["Living Room", "Bedroom", "Modern Kitchen"])
    style = st.selectbox("Style", ["Minimalist", "Industrial", "Scandinavian Luxury"])
    color = st.color_picker("Accent Color", "#3498db")
    
    generate_btn = st.button("🚀 Run Inference", use_container_width=True)

# --- 3. Main Screen ---
st.title("Hugging Face Model Integration")

if generate_btn:
    with st.spinner("Model is generating image..."):
        # Construct the Prompt for the Model
        prompt = f"Professional interior design, {style} {room}, cinematic lighting, {color} accents, high resolution"
        
        # Call the Hugging Face API
        image_bytes = query_model({"inputs": prompt})
        
        try:
            # Convert the raw bytes from the API into a displayable image
            image = Image.open(io.BytesIO(image_bytes))
            st.image(image, caption=f"Generated by Stable Diffusion v1.5", use_container_width=True)
            st.success("✅ Model inference successful!")
        except:
            st.error("Model is loading or API limit reached. Wait 10 seconds and try again.")
            # Fallback graphic
            st.markdown(f"<div style='height:200px; background:{color}22; border:2px dashed {color};'>Generating...</div>", unsafe_allow_html=True)
else:
    st.info("👈 Adjust parameters and click Run Inference to trigger the Hugging Face model.")
